// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from '/home/makini/Desktop/myapp/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import CrownOutlined from '/home/makini/Desktop/myapp/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import TableOutlined from '/home/makini/Desktop/myapp/node_modules/@ant-design/icons/es/icons/TableOutlined';
export default { SmileOutlined, CrownOutlined, TableOutlined };
